Added migrations
5Ka-me/practice pull request #7
Opened 2022-06-27 14:16 UTC by 5Ka-me

Added new entity "Category". Added migrations.

2022-06-27 15:42 UTC, hromau requested changes

2022-06-27 15:42 UTC, hromau commented on Store/DAL/Entities/Product.cs
> +        public Category Category { get; set; }
this should be 'public virtual' IINM

2022-06-27 15:42 UTC, hromau commented on Store/DAL/Interfaces/ICategoryRepository.cs
> +        Category Get(int id);
make it more clarify: GetById. naming has big role

2022-06-27 15:42 UTC, hromau commented on Store/BLL/Services/ProductService.cs
> +            if (_categoryRepository.Get(productModel.CategoryId) == null)
IMHO: a lot of IFs for validate. maybe u can try to make some kind of universal helper for validation. maybe you can look through Generics

2022-06-28 09:54 UTC, nantonov approved these changes

2022-06-29 09:32 UTC, merged